from src.data_strategies.base import DataStrategy, update_last_processed
from src.data_strategies.market import PricesPlDataStrategy
from src.data_strategies.production import ImgwDataStrategy, ImgwWindDataStrategy, ImgwSolarDataStrategy, imgw_col_ids
from src.data_strategies.consumption import HouseholdEnergyConsumptionDataStrategy
